#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# set shift+alt combination to change lang
setxkbmap -option grp:alt_shift_toggle us,ru &

# run polybar
polybar example -r >> /tmp/polybar.log 2>&1 & disown

# set wallpapers
feh --no-fehbg --bg-scale $HOME/Yandex.Disk/Wallpapers\ Full\ HD/default_arch.jpg
